# ============================================================
# LiterAlura - Configurações da Aplicação
# ============================================================

# Datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/literalura
spring.datasource.username=postgres
spring.datasource.password=1234567br
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Desabilita o banner do Spring (opcional - deixe true para ver)
spring.main.banner-mode=off

# Log level
logging.level.root=WARN
logging.level.com.alura.literalura=INFO
